apiVersion: v1
kind: Pod
metadata:
  name: redis-pod              # Name of the Pod.
  labels: 
    name: redis-pod            # Label for the Pod.
    app: demo-voting-app       # Name of the application we are keeping this same in all pod and service yaml files.
spec:
  containers:
    - name: redis              # Name of the container
      image: redis
      ports:
        - containerPort: 6379